defaults: &defaults
  token: 317eba0835b9f1229c3eecac1855d77d65f2f8a2ee751d816683e05a8ea2167321958a1bb5e95102284af3b61262e390b195dee85610b672bcc1492fb9e2f816
  app_name: Skills
  noreply: noreply@fs-skills.heroku.com
  host: localhost:3000
  identities:
    twitter:
      key: Ank92dam8rUTSfBtxN7AWg
      secret: kl95VO9BWzb6a4NL8dZJbosJMm4kmiGPoC0LKvdV6OI

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: fs-skills.heroku.com
